# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63\x32.proto\x12\x02\x63\x32\"\x19\n\x08HelloReq\x12\r\n\x05nonce\x18\x01 \x01(\x05\"\x19\n\x08HelloRes\x12\r\n\x05nonce\x18\x01 \x01(\x05\"\x0e\n\x0c\x45radicateReq\"\x0e\n\x0c\x45radicateRes\"-\n\x0ePushActionsReq\x12\x1b\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\n.c2.Action\"\x10\n\x0ePushActionsRes\"\x11\n\x0fGetPositionsReq\"2\n\x0fGetPositionsRes\x12\x1f\n\tpositions\x18\x01 \x03(\x0b\x32\x0c.c2.Position\"9\n\x08Position\x12\x10\n\x08position\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\r\n\x05state\x18\x03 \x01(\t\"\x7f\n\x06\x41\x63tion\x12\"\n\x06\x63owrie\x18\x01 \x01(\x0b\x32\x10.c2.CowrieActionH\x00\x12\x1e\n\x04suid\x18\x02 \x01(\x0b\x32\x0e.c2.SUIDActionH\x00\x12\'\n\tfake_data\x18\x03 \x01(\x0b\x32\x12.c2.FakeDataActionH\x00\x42\x08\n\x06\x61\x63tion\"\x1d\n\x0c\x43owrieAction\x12\r\n\x05start\x18\x01 \x01(\x08\"?\n\nSUIDAction\x12\r\n\x05start\x18\x01 \x01(\x08\x12\x10\n\x08old_path\x18\x02 \x01(\t\x12\x10\n\x08new_path\x18\x03 \x01(\t\"C\n\x0e\x46\x61keDataAction\x12\r\n\x05start\x18\x01 \x01(\x08\x12\x10\n\x08old_path\x18\x02 \x01(\t\x12\x10\n\x08new_path\x18\x03 \x01(\t2\xd3\x01\n\x02\x43\x32\x12%\n\x05Hello\x12\x0c.c2.HelloReq\x1a\x0c.c2.HelloRes\"\x00\x12\x31\n\tEradicate\x12\x10.c2.EradicateReq\x1a\x10.c2.EradicateRes\"\x00\x12\x37\n\x0bPushActions\x12\x12.c2.PushActionsReq\x1a\x12.c2.PushActionsRes\"\x00\x12:\n\x0cGetPositions\x12\x13.c2.GetPositionsReq\x1a\x13.c2.GetPositionsRes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQ']._serialized_start=16
  _globals['_HELLOREQ']._serialized_end=41
  _globals['_HELLORES']._serialized_start=43
  _globals['_HELLORES']._serialized_end=68
  _globals['_ERADICATEREQ']._serialized_start=70
  _globals['_ERADICATEREQ']._serialized_end=84
  _globals['_ERADICATERES']._serialized_start=86
  _globals['_ERADICATERES']._serialized_end=100
  _globals['_PUSHACTIONSREQ']._serialized_start=102
  _globals['_PUSHACTIONSREQ']._serialized_end=147
  _globals['_PUSHACTIONSRES']._serialized_start=149
  _globals['_PUSHACTIONSRES']._serialized_end=165
  _globals['_GETPOSITIONSREQ']._serialized_start=167
  _globals['_GETPOSITIONSREQ']._serialized_end=184
  _globals['_GETPOSITIONSRES']._serialized_start=186
  _globals['_GETPOSITIONSRES']._serialized_end=236
  _globals['_POSITION']._serialized_start=238
  _globals['_POSITION']._serialized_end=295
  _globals['_ACTION']._serialized_start=297
  _globals['_ACTION']._serialized_end=424
  _globals['_COWRIEACTION']._serialized_start=426
  _globals['_COWRIEACTION']._serialized_end=455
  _globals['_SUIDACTION']._serialized_start=457
  _globals['_SUIDACTION']._serialized_end=520
  _globals['_FAKEDATAACTION']._serialized_start=522
  _globals['_FAKEDATAACTION']._serialized_end=589
  _globals['_C2']._serialized_start=592
  _globals['_C2']._serialized_end=803
# @@protoc_insertion_point(module_scope)
